apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-front
  namespace: nomidot
spec:
  selector:
    matchLabels:
      app: nomidot-front
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nomidot-front
        track: stable
    spec:
      containers:
      - name: nomidot-front
        image: eu.gcr.io/test-installations-222013/nomidot-frontend@sha256:af39dfec5c8f17c69d5fceefe55b51b467b433a464bc7061ee635a88e2209cd4
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: staging