apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-server
  namespace: nomidot-staging
  labels:
    stage: staging
    name: nomidot-server
    app: nomidot-staging
spec:
  selector:
    matchLabels:
      app: nomidot-server
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: staging
        name: nomidot-server
        app: nomidot-server
    spec:
      containers:
        - name: nomidot-server
          image: eu.gcr.io/test-installations-222013/nomidot-server@sha256:e9867ba36eca38f421ce1d3994bd09e613a7c064185a1197132ca2a65a3b94ad
          env:
            - name: PRISMA_ENDPOINT
              value: http://nodewatcher.nodewatcher-staging:4466
          ports:
            - name: nomidot-4000
              containerPort: 4000