# Default values for nomidot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## common values
nodeSelector: {}

imagePullSecrets:
  - name: regcred

cloudsql:
  commandline:
    args: "-instances=<copy-from-gcp-sql-overview>"

## nodewatcher
nodewatcher:
  name: nodewatcher

  dbName: kusama-nodewatcher
  dbUser: kusama-nodewatcher
  dbPassword: from-gitlab-vars

  replicaCount: 1

  image:
    repository: prismagraphql/prisma:1.34

  service:
    type: ClusterIP
    port: 4466

frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: paritytech
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

server:
  name: server
  replicaCount: 2

  image:
    repository: paritytech
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

#  ingress:
#    enabled: false
#    annotations: {}
#      kubernetes.io/ingress.class: traefik
#    hosts:
#      - host: chart-example.local
#        paths: []
