apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomidot.nodewatcher.fullname" . }}
  labels:
    {{- include "nomidot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nomidot.nodewatcher.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "nomidot.nodewatcher.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: prisma
          image: {{ .Values.nodewatcher.image.repository }}
          ports:
            - name: prisma
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: prisma-config
                  key: prisma-config
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["cloud_sql_proxy"]
          args:
            - "--dir=/cloudsql"
            - "-credential_file=/secrets/cloudsql/credentials.json"
            - {{ .Values.cloudsql.commandline.args | quote }}
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}

