# Default values for polkassembly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

chainName: kusamaOrPolkadot
imagePullSecrets: ""
nodeSelector: {}
dockerTag: master

cloudsql:
  commandline:
    args: "-instances=<copy-from-gcp-sql-overview>=tcp:5432"
  instanceCredentials: from-gitlab-vars

nodewatcher:
  name: nodewatcher
  replicaCount: 1

  dbName: name
  dbUser: user
  dbPassword: from-gitlab-vars

  image:
    repository: prismagraphql/prisma:1.34
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 4466

  resources:
    requests:
      memory: "1280Mi"
      cpu: "250m"
    limits:
      memory: "2560Mi"
      cpu: "500m"

  tolerations: []
  affinity: {}

harvester:
  name: harvester

  image:
    repository: "eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:36bf710c39451a8054885be5bca"
    pullPolicy: Allways

  config:
    PRISMA_ENDPOINT: http://nodewatcher-service:4466
    ARCHIVE_NODE_ENDPOINT: ws://polkassembly-rpc-internal-0.parity-prod.parity.io:9944
    START_FROM: '1919357'
    BLOCK_IDENTIFIER: 'last-50k-2'
    MAX_LAG: '10'
